#index:
#    path: /
#    controller: App\Controller\DefaultController::index


app_logout:
  path: /logout
  methods: GET

ajax_search:
  path: /search
  defaults: { _controller: Stores:Default:ajax}